### ISSUE TITLE
Can I use this in a hosted build?

### ISSUE THREAD

**Issue by Kurren123** [matthid/Paket.TeamBuildCredentials#3]
I'm getting paket credential provider errors when restoring a project on the hosted build "Hosted VS2017" ([win server 2016 with vs 2017](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#use-a-microsoft-hosted-agent)).

```
Source 'https://.../nuget/v3/index.json' exception: System.Exception: error ---> System.Exception: Could not retrieve data from 'https://....pkgs.visualstudio.com/_packaging/.../nuget/v2/Packages?$filter=... ---> Paket.NetUtils+RequestFailedException: Request to 'https://....pkgs.visualstudio.com/_packaging/.../nuget/v2/Packages?$filter=... failed with: 401 Unauthorized - TF400813: Resource not available for anonymous access. Client authentication required.
```

Is there any way to set up the credential provider in a hosted build? Thanks!

**Comment by matthid** [comment]
Yes it should work, are you using https://marketplace.visualstudio.com/items?itemName=isaacabraham.fsharp-helpers-extension or some other version?

**Comment by Kurren123** [comment]
Thanks @matthid for replying. I can see how this would work using the builder UI (just add the extension and use) but I'm not sure how this would work with an azure pipelines yaml build (which is what it looks like they are pushing at the moment). I'd be greatful for any info! Thanks again

**Comment by matthid** [comment]
It looks similar with yaml: https://dev.azure.com/fakebuild/FSProjects/_git/Test_Extensions?path=%2F.azure-pipelines.yml&version=GBmaster

Problem is that the guids I'm using here are not correct and I have not yet documented this stuff as I'd like to simplify/change them, however you can retrieve the guids by downloading the vsix extension (by choosing on-premise tfs you get the download in the marketplace) and extracting it (it is a normal zip file) then take a look at the manifest and the task.json

You can use the same 'trick' for all extensions

**Comment by Kurren123** [comment]
Hi @matthid. Sorry for the late reply but I'm having trouble getting this to work. I'm using F# Helpers for Azure DevOps, downloaded the vsix and have copied the GUIDs as instructed. The extension is installed and activated but devops is complaining that the step does not exist. My YAML file:

```yaml
trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

# Paket - Setup Credentials Manager
- task: matthid.paket-private.5bfdd7ca-9bf4-40f7-b753-fd674e7ff85c.setCredentialManager@0
  displayName: 'Setup Paket Credential Manager'
  
- script: ./.paket/paket.exe restore
  displayName: 'Restore Paket'

# Paket - Clean up Credentials Manager
- task: matthid.paket-private.33416f37-5fe8-488d-a2aa-48f52e7a14f9.paketCredentialCleanup@0
  displayName: 'Cleanup Paket credential manager'
```

Am I meant to replace `matthid.paket-private.` with something else?

Thanks,

Kurren
